Allow setting the directory where to store the screenshots
aloetesting/aloe_webdriver pull request #34
Opened 2017-02-20 00:29 UTC by jricardo27

2017-02-20 06:14 UTC, koterpillar commented on aloe_webdriver/screenshot_failed.py
> +if 'SCREENSHOT_DIR' not in globals():
Why not define the constant the normal way?

2017-02-20 06:15 UTC, koterpillar commented on aloe_webdriver/screenshot_failed.py
> +        os.makedirs(directory)
`os.makedirs(directory, exist_ok=True)`

2017-02-20 06:17 UTC, koterpillar commented on aloe_webdriver/screenshot_failed.py
> +    if SCREENSHOT_DIR:
It should be possible to achieve this with `FORMAT` alone, just use `dirname` on `base_name`.

2017-02-20 06:18 UTC, koterpillar commented on aloe_webdriver/tests/test_screenshot_failed.py
> +        # Delete temporal directory if any.
"temporary directory", not "temporal" (here and below).

2017-02-20 06:19 UTC, koterpillar commented on aloe_webdriver/screenshot_failed.py
> +def set_save_directory(directory):
It is possible to set `aloe_webdriver.screenshot_failed.FORMAT` (and `SCREENSHOT_DIR` with your changes) directly. Why the extra functions?

2017-02-20 06:20 UTC, koterpillar commented on aloe_webdriver/screenshot_failed.py
> +def unset_save_directory():
This looks like it's only useful within tests.

2017-02-20 06:20 UTC, koterpillar commented on aloe_webdriver/screenshot_failed.py
> +    """Unset the directory fr saving screenshots."""
Typo.

2017-02-20 06:24 UTC, koterpillar requested changes
If you want, merge `FORMAT` and `SCREENSHOT_DIR` into one and point out that it can include the directory names in the documentation.

The tricks with `globals()` shouldn't be necessary even in tests, because the module is reloaded anyway. _If_ for some reason it's unavoidable, there should be a comment explaining why.

2017-02-21 03:17 UTC, jricardo27 commented
- Preferred to leave `FORMAT` and `SCREENSHOT_DIR` separate as is easier to enforce a slash at the end of the directory by using `os.path.join`. Removed the extra `if` though.

- Updated the documentation.

- Removed unnecessary functions.

- Still need to use the trick with `globals()` as the problem is precisely the module being reloaded on tests and resetting the `SCREENSHOT_DIR` value. Added a note about that.

2017-02-21 21:31 UTC, koterpillar commented
Interesting, I doubted that `globals` was necessary. Here's what I found:

* `reload(aloe_webdriver.screenshot_failed)` is triggered by an environment variable set in tests. I suspect in your real test suite you set the directory from a steps file too, so why not add another environment variable to control the directory? E.g.

```python

2017-02-21 21:42 UTC, koterpillar requested changes
Interesting, I doubted that `globals` was necessary. Here's what I found: `reload(aloe_webdriver.screenshot_failed)` is triggered by an environment variable set in tests. I suspect in your real test suite you set the directory from a steps file too, so why not add another environment variable to control the directory? E.g.
```python
if os.environ.get('TAKE_SCREENSHOTS'):
    # Only register the screenshot steps if asked to
    import aloe_webdriver.screenshot_failed
    reload(aloe_webdriver.screenshot_failed)

    screenshot_dir = os.environ.get('SCREENSHOT_DIR')
    if screenshot_dir:
        aloe_webdriver.screenshot_failed.SCREENSHOT_DIR = screenshot_dir
```

Also, `screenshot_failed.SCREENSHOT_DIR` is redundant, as it will always be used qualified. Rename to `DIRECTORY`.

2017-02-21 21:42 UTC, koterpillar commented on aloe_webdriver/screenshot_failed.py
> +``SCREENSHOT_DIR`` as follow:
"as follows"

2017-02-21 21:42 UTC, koterpillar commented on aloe_webdriver/screenshot_failed.py
> +#  prevents it to be reset.
"prevents it from being reset" (but irrelevant, because the `globals` trick isn't needed)

2017-02-21 22:41 UTC, jricardo27 commented
Updated.

2017-02-22 02:44 UTC, koterpillar commented
The build failed, please fix.

2017-02-22 09:50 UTC, jricardo27 commented
Just a couple failed due to timeout when downloading a Docker image.

How can I run them again?

```
docker: error pulling image configuration: Get https://dseasb33srnrn.cloudfront.net/registry-v2/docker/registry/v2/blobs/sha256/1a/1a2c5a5ec0336adb8bfdcd9cd5961e3fc1071899546f83fa4628b58fcd29c5c7/data?Expires=1487726891&Signature=hLmBcBC9v3xCTsWnmTAHnUC9Gh9ZhXrknn4ft5f2fPD6EDyjH6LQwm~Bf13w-Js1FarxgKlvzHvFxjNUpYkWnDVHLtk2bUAbKtyuRQCSmKj03fWIJauL1agh4M527aFqNeKLYEM2nSWDk1B7rhpb7f4Jgkfgb8q4sP9JyP9w2xo_&Key-Pair-Id=APKAJECH5M7VWIS5YZ6Q: net/http: TLS handshake timeout.
```

2017-02-22 20:40 UTC, koterpillar approved these changes

2017-02-22 20:40 UTC, merged

2017-02-22 20:57 UTC, koterpillar commented
Merged, will be released by Travis shortly. Thanks!